language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

env:
  global:
    - COVERAGE=false
    - PHPUNIT_ARGS=''

matrix:
  fast_finish: true
  include:
    - php: '7.2'
      env:
        - COVERAGE=true
        - PHPUNIT_ARGS="--coverage-text"

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer install --no-interaction

script:
  - php vendor/bin/phpunit ${PHPUNIT_ARGS}
  - php vendor/bin/phpcs --standard=PSR2 src
  - php vendor/bin/phpcpd src

